//
//  ejDefTwo.swift
//  EnvironmentalJusticeReadOnly
//
//  Created by Sasha on 6/11/21.
//

import Foundation



let ejDef = " \"Environmental justice is the fair treatment and meaningful involvement of all people regardless of race, color, national origin, or income, with respect to the development, implementation, and enforcement of environmental laws, regulations, and policies. \n \n This goal will be achieved when everyone enjoys: \n \n • The same degree of protection from environmental and health hazards, and \n • Equal access to the decision-making process to have a healthy environment in which to live, learn, and work.\" \n \n - U.S. EPA"

let citations = "https://www.atomicheritage.org/location/los-alamos-nm \n https://sites.coloradocollege.edu/ejsw/2016/11/17/environmental-injustices-for-pueblo-communities-near-los-alamos-national-laboratory/ \n https://en.wikipedia.org/wiki/Los_Alamos_National_Laboratory /n https://www.nbcnews.com/news/latino/50-years-later-remembering-delano-grape-strike-n433886 \n https://www.pugetsound.edu/faculty-pages/dsackman/senior-theses/tiffany-dyer/ \n https://tavaana.org/en/en/content/fighting-farm-workers-rights-cesar-chavez-delano-grape-strike-and-boycott \n https://en.wikipedia.org/wiki/United_Farm_Workers \n https://exchangeproject.unc.edu/wp-content/uploads/sites/18406/2018/08/Real-People-Afton-summary-07-0320.pdf \n https://timeline.com/warren-county-dumping-race-4d8fe8de06cb \n https://www.ncdcr.gov/blog/2013/02/26/a-watershed-moment-for-environmental-justice-the-warren-county-pcb-protests \n https://www.nytimes.com/1982/08/11/us/carolinians-angry-over-pcb-landfill.html \n https://en.wikipedia.org/wiki/Warren_County_PCB_Landfill \n https://digitalcommons.law.ggu.edu/gguelj/vol1/iss1/7/ \n https://www.dhs.wisconsin.gov/publications/p4/p45014.pdf \n https://ir.lawnet.fordham.edu/cgi/viewcontent.cgi?article=1405&context=ulj \n http://www.umich.edu/~snre492/ny.html \n https://medium.com/nycwater/resource-recovery-north-river-style-1e830ec2185e \n https://www.env.nm.gov/general/wp-content/uploads/sites/10/2016/08/2019-07-31-2019-Tribal-Report.pdf \n https://hwbdocuments.env.nm.gov/Los%20Alamos%20National%20Labs/General/13616.PDF \n http://weact.nyc/tabid/180/Default.aspx \n http://www.rootsofhealthinequity.org/assets/downloads/neighborhood_fights_back_transcript.pdf \n https://www.ncpedia.org/pcb-protests \n https://timeline.com/warren-county-dumping-race-4d8fe8de06cb \n https://ufw.org/organizing/key-campaigns/ \n https://www.nrdc.org/stories/environmental-justice-movement \n https://escholarship.org/content/qt0ft5n1qr/qt0ft5n1qr.pdf?t=mv2j9e \n https://core.ac.uk/download/pdf/217211287.pdf"

let warrenSheet = "The actions taken against the Warren County PCB Landfill sparked the formation of community groups taking a stand to combat environmental justice issues throughout the country. This led to the EPA reviewing their processes regarding site selection of hazardous waste facilities. In 1987 a report was released by the United Church of Christ stating that “three out of five African Americans and Hispanics live in a community housing toxic waste”. This confirmed that the government was placing hazardous sites in areas that were predominantly poor and had residents of color. This prompted President Clinton to sign an executive order in 1994 directing “federal agencies to identify and address disproportionately high adverse health or environmental effects of their policies or programs on low-income people and people of color.” Today, environmental justice groups are continuing to raise awareness and are working towards a more healthful environment for all."
let hawkinsSheet = "Hawkins v. Town of Shaw became the model for municipal cases that violate the Fourteenth Amendment. Following this case, the court developed a new test to determine if local governments actions were indeed a violation of the Equal Protection Clause. The elements of the test were: “(1) the existence of racially identifiable neighborhoods in the municipality; (2) substantial inferiority in the quality or quantity of the municipal services in question; and (3) proof of intent or motive.” Statistical disparities in the distribution of municipal services and proof of residential segregation proved to be present in Johnson v. City of Arcadia and subsequent cases that resembled Hawkins v. Town of Shaw."
let northSheet = "The organization WE ACT was established in 1988 as a result of the injustices surrounding the sewage treatment plant in West Harlem. Throughout the years, WE ACT has met with local and state officials regarding the environmental injustices in the community. With the goal of defending a person’s quality of life in mind, the organization has helped to reform environmental policy, educate the community on environmental health and regulation, and help the environmental justice movement on a national and global scale."
